package rules.address

import com.fintech.modules.drools.example.address.entity.Address;
import com.fintech.modules.drools.example.address.entity.AddressCheckResult;

rule "Postcode should be filled with exactly 5 numbers"

    when
        address : Address(postCode!= null, postCode matches "([0-9]{5})")
        checkResult : AddressCheckResult();
    then
        checkResult.setPostCodeResult(true);
        System.out.println("规则中打印日志：校验通过!");
end